Updating dbt-core to v1.5
cloudera/dbt-impala pull request #191
Opened 2024-02-16 12:09 UTC by nsharma-25

## Describe your changes
Updated the dbt-core to v1.5

## Internal Jira ticket number or external issue link
https://jira.cloudera.com/browse/DBT-760

## Testing procedure/screenshots(if appropriate):

## Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] I have formatted my added/modified code to follow pep-8 standards
- [ ] I have checked suggestions from python linter to make sure code is of good quality.

2024-02-20 21:00 UTC, vamshikolanu requested changes

2024-02-20 21:00 UTC, vamshikolanu commented on .gitignore
> -.venv/
Why is this change required ? Can you move it to a different PR if you have a valid reasoning for it ?

2024-02-26 16:28 UTC, niteshy commented
How do you know if the dbt-core version is upgraded to 1.5.x ?

2024-02-26 16:42 UTC, nsharma-25 commented
> How do you know if the dbt-core version is upgraded to 1.5.x ?
I checked it by running the `dbt --version` command. The installed dbt-core version is 1.5.9.

2024-05-14 15:30 UTC, closed without merging